# Generated by Django 2.0.2 on 2020-04-02 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 8, 19, 17, 87601, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
